/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.davidgracia.software.authorizationmanager.sdk.kotlin

import kotlin.test.Test

class LibraryTest {
    @Test fun testSomeLibraryMethod() {
        val instance = "myInstance"
        val apiKey = "apiKey"
        val authorizationManagerClient = AuthorizationManagerClient(instance = instance, apiKey = apiKey)

        val resource = Resource()
        authorizationManagerClient.save(resource)

        val permission = Permission()
        authorizationManagerClient.save(permission)

        val resourcePermission = ResourcePermission(resource, permission)
        authorizationManagerClient.save(resourcePermission)

        val role = Role(setOf(resourcePermission))
        authorizationManagerClient.save(role)

        val resourceRolePermission = ResourceRolePermission(resource, role, permission)
        authorizationManagerClient.save(resourceRolePermission)

        val user = User(setOf(role))
        authorizationManagerClient.save(user)
    }
}

