/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.davidgracia.software.authorizationmanager.sdk.kotlin

class Library {
    fun someLibraryMethod(): Boolean {
        return true
    }
}
